name: Create PR Environment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-app:
    name: Configure DigitalOcean App
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        shell: bash
        run: |
          echo ${GITHUB_HEAD_REF#refs/heads/} \
             | tee head.ref
          echo "::set-output name=branch::$(cat head.ref)"
        id: extract

      - name: Transform Branch Name
        shell: bash
        env:
          BRANCH_NAME: ${{ steps.extract.outputs.branch }}
        run: |
          echo $BRANCH_NAME \
             | tr '_./' '-' \
             | tr -Cd '[:alnum:]-\n' \
             | tee branch.name
          echo "::set-output name=app_name::$(cat branch.name)"
        id: tr

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Write App Spec
        env:
          APP_NAME: ${{ steps.tr.outputs.app_name }}
          BRANCH_NAME: ${{ steps.extract.outputs.branch }}
        run: |
          cat <<EOF >app.yaml
          name: pr-$APP_NAME
          region: nyc
          services:
            - name: api
              dockerfile_path: api/Dockerfile-pr
              github:
                repo: ${{ github.repository }}
                branch: $BRANCH_NAME
                deploy_on_push: true
              health_check:
                http_path: /v1/health
              instance_size_slug: basic-xs
              envs:
                - key: SPACES_ACCESS_KEY_ID
                  value: ${{ secrets.DIGITAL_OCEAN_SPACES_KEY }}
                  scope: RUN_TIME
                  type: SECRET
                - key: SPACES_SECRET_ACCESS_KEY
                  value: ${{ secrets.DIGITAL_OCEAN_SPACES_SECRET }}
                  scope: RUN_TIME
                  type: SECRET
                - key: SPACES_HOSTNAME
                  value: "https://nyc3.digitaloceanspaces.com"
                  scope: RUN_TIME
                - key: SPACES_REGION
                  value: "nyc3"
                  scope: RUN_TIME
                - key: SPACES_BUCKET_PREFIX
                  value: "u1o.dev"
                  scope: RUN_TIME
            - name: phonebook
              dockerfile_path: Dockerfile
              envs:
              - key: PLIVO_APP_ID
                scope: RUN_TIME
                value: "31519918106914646"
              - key: PLIVO_AUTH_ID
                scope: RUN_TIME
                # type: SECRET
                value: ${{ secrets.PLIVO_AUTH_ID }}
              - key: PLIVO_AUTH_TOKEN
                scope: RUN_TIME
                # type: SECRET
                value: ${{ secrets.PLIVO_AUTH_TOKEN }}
              - key: AWS_ACCESS_KEY_ID
                scope: RUN_TIME
                type: SECRET
                value: ${{ secrets.DIGITAL_OCEAN_SPACES_KEY }}
              - key: AWS_SECRET_ACCESS_KEY
                scope: RUN_TIME
                type: SECRET
                value: ${{ secrets.DIGITAL_OCEAN_SPACES_SECRET }}
              - key: PHONEBOOK_BUCKET
                scope: RUN_AND_BUILD_TIME
                value: phonebook.u1o.dev
              - key: MAILBOX_BUCKET
                scope: RUN_AND_BUILD_TIME
                value: mailboxes.u1o.dev
              - key: AWS_S3_ENDPOINT
                scope: RUN_AND_BUILD_TIME
                value: nyc3.digitaloceanspaces.com
              github:
                branch: main
                deploy_on_push: true
                repo: withuno/phonebook
              http_port: 8080
              instance_count: 1
              instance_size_slug: basic-xxs
              internal_ports:
              - 80
              routes:
              - path: /phonebook
              source_dir: /
          EOF

      - name: Create New App
        run: |
          doctl app create --spec app.yaml --no-header --format ID 2>/dev/null \
             | tee app.id
          echo "::set-output name=id::$(cat app.id)"
        id: app

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Started deployment https://cloud.digitalocean.com/apps/${{ steps.app.outputs.id }}/deployments"

